name: Deploy - PROD

on:
  push:
    branches:
      - main

jobs:
  upload-realtime-printer-to-scaleway:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SERVER_HOST}}
          username: ${{secrets.SERVER_USER}}
          password: ${{secrets.SERVER_PWD}}
          script: |
            /home/scripts/mails.sh