# name: Deploy - PROD

# on:
#   push:
#     branches:
#       - main

# jobs:
#   upload-realtime-printer-to-scaleway:
#     runs-on: ubuntu-latest
#     steps:
#       - name: executing remote ssh commands using ssh key
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{secrets.SERVER_HOST}}
#           username: ${{secrets.SERVER_USER}}
#           password: ${{secrets.SERVER_PWD}}
#           script: |
#             /home/scripts/mails.sh


name: Publish Docker image

on:
  push:
    branches: 
      - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: acnodu/mails
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}