name: Build & Publish Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: main

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
          
    # Set environment variables
    - run: echo VERSION=$(cat ./package.json | jq -r .version) >> $GITHUB_ENV
    - run: echo NAME=$(cat ./package.json | jq -r .name) >> $GITHUB_ENV
    
    - name: Overwrite Public Version
      uses: "DamianReeves/write-file-action@master"
      with:
        path: ./public/version.json
        write-mode: overwrite
        contents: |
          "${{env.VERSION}}"

    - name: Overwrite Compiled Version
      uses: "DamianReeves/write-file-action@master"
      with:
        path: ./src/assets/version.json
        write-mode: overwrite
        contents: |
          "${{env.VERSION}}"

    # Build & Publish
    - name: Build & Publish Docker Image (acnodu/${{env.NAME}}:${{ env.VERSION }})
      uses: docker/build-push-action@v2
      with:
        push: true
        context: .
        tags: acnodu/${{env.NAME}}:latest, acnodu/${{env.NAME}}:${{ env.VERSION }}

    # Update Readme
     - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: acnodu/${{env.NAME}}
        readme-filepath: ./README.md